print("La Liga 2019-20 Season Data")
print()
laliga = open("LaLiga.csv")
print(laliga.read())
laliga.close()

print("Seria A 2019-20 Season Data")
print()
seriea = open("SerieA.csv", "w")
seriea.write("Juventus will win the Serie A")
seriea.close()
seriea = open("SerieA.csv")
print(seriea.readlines())
seriea.close()

print("Premier League 2019-20 Season Data")
print()
epl = open("EPL.csv","a")
epl.write("23/08/2019,20:00,Aston Villa,Everton,0,1")
epl.close()
epl = open("EPL.csv")
print(epl.read())

with open("Ligue1.csv") as ligue1, open("Eredivisie.csv") as eredivisie:
	print("Ligue 1 2019-20 Season Data")
	print()
	print(ligue1.read())
	ligue1.close()
	print("Eredivisie 2019-20 Season Data")
	print()
	print(eredivisie.read())
	eredivisie.close()

import os
curr_path = os.getcwd()
print (curr_path)
os.chdir("D:\Consultadd\Main_Training\Assignment_2")
changed_path = os.getcwd()
print (changed_path)
print("Change of directory successful!!!")