# Generated by Django 2.2 on 2019-09-09 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_game'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='example',
            options={'verbose_name_plural': 'Example'},
        ),
    ]
