# Generated by Django 2.2 on 2019-09-09 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190908_2040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={'verbose_name_plural': 'Football Club'},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name_plural': 'Game'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name_plural': 'Film'},
        ),
    ]
