# Generated by Django 2.2 on 2019-09-19 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_profiles_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profiles',
        ),
    ]
